import test from 'node:test';
import assert from 'node:assert/strict';
import {Store} from '../src/store.js';
import {Observations, BudgetError} from '../src/observations.js';
const settings={effort:'low',toolScope:'conversation',timeout:180};
function fixture(){const store=new Store(':memory:');return {store,o:store.observations};}
function attempt(o,r,thread,fresh=false){return o.attempt(r,settings,'main',thread,fresh);}
function completed(o,a,input,output){o.finishAttempt(a,'completed',{input_tokens:input,output_tokens:output,cached_input_tokens:0,cache_write_input_tokens:0});}
function receipts(store){return store.db.prepare('SELECT payload FROM attempt_observations ORDER BY rowid').all().map(r=>JSON.parse(r.payload));}
test('serialized cumulative receipts, duplicate terminal, and synthesized write zero',()=>{const {store,o}=fixture();const r=o.run();const a=attempt(o,r,'thread',true);completed(o,a,100,20);o.finishAttempt(a,'provider_error');const b=attempt(o,r,'thread');completed(o,b,160,30);const rows=receipts(store);assert.equal(rows.length,2);assert.deepEqual(rows.map(v=>v.delta.input_tokens),[100,60]);assert.deepEqual(rows.map(v=>v.delta.output_tokens),[20,10]);assert.equal(rows[1].usage.input_tokens,160);assert.equal(rows[1].cacheWriteProvenance,'unknown_sdk_default');assert.equal(rows[1].usage.cache_write_input_tokens,undefined);store.db.close();});
test('unknown, failure, reset, restart and concurrent gaps never invent deltas',()=>{const {store,o}=fixture();const r=o.run();let a=attempt(o,r,'unknown');completed(o,a,100,20);assert.equal(receipts(store).at(-1).delta,null);a=attempt(o,r,'unknown');o.finishAttempt(a,'cancelled');a=attempt(o,r,'unknown');completed(o,a,160,30);assert.equal(receipts(store).at(-1).delta,null);a=attempt(o,r,'unknown');completed(o,a,5,1);assert.equal(receipts(store).at(-1).delta,null);const b=attempt(o,r,'unknown'),c=attempt(o,r,'unknown');completed(o,b,10,2);completed(o,c,15,3);assert.equal(receipts(store).at(-1).delta,null);const reopened=new Observations(store);a=attempt(reopened,reopened.run(),'unknown');completed(reopened,a,20,4);assert.equal(receipts(store).at(-1).delta,null);store.db.close();});
test('strict fresh schema drops private/unknown fields and telemetry failures are isolated',()=>{const {store,o}=fixture();assert.equal(o.record({canary:'PRIVATE_CANARY'}),false);assert.equal(o.dropped,1);const r=o.run(),a=attempt(o,r,'private-thread',true);o.finishAttempt(a,'provider_error',{input_tokens:'PRIVATE_CANARY',unknown:'PRIVATE_CANARY'});assert.equal(JSON.stringify(receipts(store)).includes('PRIVATE_CANARY'),false);store.db.exec('DROP TABLE attempt_observations');assert.doesNotThrow(()=>o.finishAttempt(attempt(o,r,'other',true),'completed',{input_tokens:1,output_tokens:1}));assert.ok(o.dropped>1);store.db.close();});
test('budgets accumulate across attempts and preserve capability counts on rejection',()=>{const {store,o}=fixture();const r=o.run({tools:1,artifacts:5});const a=attempt(o,r,'t',true);completed(o,a,1,1);o.tool(r,'history_read');const b=attempt(o,r,'t');assert.throws(()=>o.tool(r,'TENANT_CANARY'),BudgetError);assert.equal(r.tools,2);o.finishAttempt(b,'budget');assert.throws(()=>o.artifact(r,6),BudgetError);o.finishRun(r,'completed');o.finishRun(r,'provider_error');assert.equal(store.db.prepare('SELECT count(*) n FROM run_observations WHERE terminal IS NOT NULL').get().n,1);assert.equal(JSON.stringify(receipts(store)).includes('TENANT_CANARY'),false);store.db.close();});

import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {Codex} from '@openai/codex-sdk';
import {Agent} from '../src/agent.js';
import {Service} from '../src/service.js';
import {config} from '../src/config.js';
async function sdkFixture(t){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'private-observations-'));const cfg=config({TELEGRAM_ALLOWED_USER_IDS:'123',WORKSPACE_DIR:dir,CODEX_HOME:path.join(dir,'codex'),BROWSER_ENABLED:'false'});const store=new Store(path.join(dir,'state.sqlite'));const service=new Service(cfg,store,{},{});await service.init();const binary=path.join(dir,'synthetic-codex');const capability=(...args)=>service.capability(...args);capability.release=token=>service.releaseCapability(token);const agent=new Agent(cfg,store,capability,options=>new Codex({...options,codexPathOverride:binary}));service.agent=agent;t.after(async()=>{store.db.close();await fs.rm(dir,{recursive:true,force:true});});return {dir,cfg,store,service,agent,binary,async events(events){const lines=typeof events==='string'?events:events.map(e=>JSON.stringify(e)).join('\n');await fs.writeFile(binary,`#!/usr/bin/env node\nprocess.stdin.resume();process.stdin.on('end',()=>process.stdout.write(${JSON.stringify(lines+'\n')}));\n`,{mode:0o700});}};}
const success=(input=100,output=20,files=[])=>[{type:'thread.started',thread_id:'private-thread-canary'}, {type:'item.completed',item:{type:'agent_message',id:'private-item-canary',text:JSON.stringify({text:'Content canary',voice:false,files})}},{type:'turn.completed',usage:{input_tokens:input,output_tokens:output,cached_input_tokens:0}}];
test('actual pinned parser omission, resumed totals, and SDK content canaries stay out of observations',async t=>{const f=await sdkFixture(t);const events=success();events.splice(1,0,{type:'item.completed',item:{type:'reasoning',text:'RAW_PRIVATE_CANARY',command:'RAW_PRIVATE_CANARY',path:'RAW_PRIVATE_CANARY',url:'RAW_PRIVATE_CANARY',error:{message:'RAW_PRIVATE_CANARY',stack:'RAW_PRIVATE_CANARY'},unknown:'RAW_PRIVATE_CANARY'}});events.at(-1).usage.unknown='RAW_PRIVATE_CANARY';events.at(-1).unknown='RAW_PRIVATE_CANARY';await f.events(events);await f.agent.run('123','RAW_PRIVATE_CANARY');await f.events(success(160,30));await f.agent.run('123','RAW_PRIVATE_CANARY');const rows=receipts(f.store);assert.deepEqual(rows.map(p=>p.delta.input_tokens),[100,60]);assert.equal(rows[0].cacheWriteProvenance,'unknown_sdk_default');assert.equal(rows[0].usage.cache_write_input_tokens,undefined);const observations=f.store.db.prepare('SELECT payload FROM run_observations UNION ALL SELECT payload FROM attempt_observations').all();assert.equal(JSON.stringify(observations).includes('RAW_PRIVATE_CANARY'),false);assert.equal(JSON.stringify(observations).includes('private-thread-canary'),false);assert.equal(f.service.capabilities.size,0);assert.match(rows[0].promptHash,/^[a-f0-9]{64}$/);assert.match(rows[0].toolsHash,/^[a-f0-9]{64}$/);});
test('actual pinned parser safely classifies malformed, quota, invalid output and incomplete streams',async t=>{const f=await sdkFixture(t);for(const [events,reason] of [['MALFORMED_PRIVATE_CANARY','provider_error'],[[{type:'turn.failed',error:{message:'RAW_ERROR_CANARY',code:'quota_exceeded',stack:'RAW_STACK_CANARY'}}],'quota'],[[...success().slice(0,1),{type:'item.completed',item:{type:'agent_message',text:'INVALID_PRIVATE_CANARY'}},success().at(-1)],'invalid_output'],[success().slice(0,-1),'incomplete_stream']]){await f.events(events);await assert.rejects(f.agent.run('123','input'));const row=receipts(f.store).at(-1);assert.equal(row.reason,reason);assert.equal(row.delta,null);assert.equal(JSON.stringify(row).includes('CANARY'),false);}assert.equal(f.service.capabilities.size,0);});
test('crash recovery writes one unknown terminal and invalidates previous baseline',()=>{const {store,o}=fixture();const r=o.run();const a=attempt(o,r,'thread',true);new Observations(store);assert.equal(receipts(store).length,1);assert.equal(receipts(store)[0].reason,'recovered_interruption');assert.equal(receipts(store)[0].usage,null);assert.equal(store.db.prepare('SELECT terminal FROM run_observations WHERE id=?').get(r.id).terminal,'recovered_interruption');store.db.close();});
test('observed token gate applies only to next attributable attempt; unknown spend remains unknown',()=>{const {store,o}=fixture();const r=o.run({tokens:100});completed(o,attempt(o,r,'fresh',true),100,20);assert.doesNotThrow(()=>o.artifact(r,5));assert.throws(()=>attempt(o,r,'fresh'),BudgetError);const unknown=o.run({tokens:1});o.finishAttempt(attempt(o,unknown,'resumed'),'cancelled');assert.doesNotThrow(()=>attempt(o,unknown,'resumed'));o.finishRun(unknown,'cancelled');assert.equal(JSON.parse(store.db.prepare('SELECT payload FROM run_observations WHERE id=?').get(unknown.id).payload).inputTokens,null);store.db.close();});
test('service final artifacts count cumulatively and exhaustion produces one budget terminal',async t=>{const f=await sdkFixture(t);f.cfg.runBudgets.artifacts=10;await fs.mkdir(path.join(f.dir,'outputs'),{recursive:true});const files=['a.txt','b.txt'].map(n=>path.join(f.dir,'outputs',n));for(const file of files)await fs.writeFile(file,'123456');await f.events(success(100,20,files));const jobId=f.store.job('123','Synthetic task');f.store.db.prepare("UPDATE jobs SET state='running' WHERE id=?").run(jobId);const job=f.store.db.prepare('SELECT * FROM jobs WHERE id=?').get(jobId);await f.service.runJob(job,new AbortController());assert.equal(f.store.db.prepare('SELECT state FROM jobs WHERE id=?').get(jobId).state,'failed');const runs=f.store.db.prepare('SELECT terminal,payload FROM run_observations').all();assert.equal(runs.length,1);assert.equal(runs[0].terminal,'budget');assert.equal(JSON.parse(runs[0].payload).artifactBytes,12);assert.equal(receipts(f.store)[0].reason,'completed');assert.equal(f.store.db.prepare('SELECT count(*) n FROM outbox WHERE artifact_id IS NOT NULL').get().n,0);});
test('failed final file preparation cannot mark a successful logical run',async t=>{const f=await sdkFixture(t);await f.events(success(100,20,[path.join(f.dir,'outputs','missing')]));const id=f.store.job('123','Synthetic task');f.store.db.prepare("UPDATE jobs SET state='running' WHERE id=?").run(id);await f.service.runJob(f.store.db.prepare('SELECT * FROM jobs WHERE id=?').get(id),new AbortController());assert.equal(f.store.db.prepare('SELECT terminal FROM run_observations').get().terminal,'output_error');});
test('host service tools retain capability counts and abort shared run on exhaustion',async t=>{const f=await sdkFixture(t);const controller=new AbortController(),r=f.store.observations.run({tools:1},controller);const token=f.service.capability('123',false,false,controller.signal,{observationRun:r});const cap=f.service.capabilities.get(token);await f.service.tool(cap,'history_read');await assert.rejects(f.service.tool(cap,'history_read'),BudgetError);assert.equal(cap.toolCounts.total,2);assert.equal(r.toolCounts.history,2);assert.equal(controller.signal.aborted,true);f.service.releaseCapability(token);});
test('wall budget spans run preparation and abort propagates',async()=>{const {store,o}=fixture();const ctrl=new AbortController(),r=o.run({wallMs:15},ctrl);await new Promise(resolve=>setTimeout(resolve,25));assert.equal(ctrl.signal.aborted,true);o.finishRun(r,'timeout');assert.equal(store.db.prepare('SELECT terminal FROM run_observations').get().terminal,'budget');store.db.close();});
test('multiple conversation connections share epoch and never recover active runs',async t=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'observation-connections-')),file=path.join(dir,'state.sqlite');t.after(()=>fs.rm(dir,{recursive:true,force:true}));const first=new Store(file),o=first.observations,r=o.run(),a=attempt(o,r,'thread',true);const second=new Store(file);assert.equal(second.observations.epoch,o.epoch);assert.equal(first.db.prepare('SELECT terminal FROM run_observations').get().terminal,null);completed(o,a,100,20);completed(second.observations,attempt(second.observations,second.observations.run(),'thread'),160,30);assert.equal(receipts(first).at(-1).delta.input_tokens,60);first.db.close();second.db.close();const reopened=new Store(file);const b=attempt(reopened.observations,reopened.observations.run(),'thread');completed(reopened.observations,b,200,40);assert.equal(receipts(reopened).at(-1).delta,null);reopened.db.close();});
test('external-use uncertainty explicitly invalidates same-thread attribution',()=>{const {store,o}=fixture(),r=o.run();completed(o,attempt(o,r,'thread',true),100,20);o.invalidateThread('thread');completed(o,attempt(o,r,'thread'),160,30);assert.equal(receipts(store).at(-1).delta,null);store.db.close();});
test('schema versions and nested private fields fail closed; numeric runtime is measured',()=>{const {store,o}=fixture(),r=o.run(),a=attempt(o,r,'thread',true);const p=o.receipt(a,'completed',{input_tokens:1,output_tokens:1,cached_input_tokens:0},'supported_complete');assert.equal(p.schema_version,1);assert.equal(p.runtime.nodeMajor,Number(process.versions.node.split('.')[0]));assert.equal(p.application_release,'0.1.0');assert.equal(o.record({...p,schema_version:2}),false);assert.equal(o.record({...p,settings:{...p.settings,unknown:'PRIVATE_CANARY'}}),false);assert.equal(o.record({...p,runtime:{...p.runtime,unknown:'PRIVATE_CANARY'}}),false);assert.equal(o.record({...p,usage:{...p.usage,unknown:'PRIVATE_CANARY'}}),false);assert.equal(receipts(store).length,0);store.db.close();});
test('observation initialization failures preserve agent execution and safe drops',async t=>{const f=await sdkFixture(t);f.store.db.exec('DROP TABLE attempt_observations');await f.events(success());assert.equal((await f.agent.run('123','synthetic input')).text,'Content canary');assert.ok(f.store.observations.dropped>0);});
test('thread overlap leaves the next completion unattributed before serialized baseline resumes',()=>{const {store,o}=fixture(),r=o.run();completed(o,attempt(o,r,'thread',true),100,20);const a=attempt(o,r,'thread'),b=attempt(o,r,'thread');completed(o,a,160,30);completed(o,b,200,40);completed(o,attempt(o,r,'thread'),220,45);assert.equal(receipts(store).at(-1).delta,null);completed(o,attempt(o,r,'thread'),230,50);assert.equal(receipts(store).at(-1).delta.input_tokens,10);store.db.close();});
test('prototype-like SDK tool names map to other and never become categories',()=>{const {store,o}=fixture(),r=o.run();for(const name of ['__proto__','constructor','TENANT_CANARY'])o.tool(r,name);o.finishRun(r,'completed');assert.deepEqual(JSON.parse(store.db.prepare('SELECT payload FROM run_observations').get().payload).toolCounts,{other:3});store.db.close();});
test('malformed parser content remains absent from main service failure logs and persisted receipts',async t=>{const f=await sdkFixture(t);await f.events('MALFORMED_LOG_CANARY');f.store.ingest(1,'123',{text:'Synthetic input'});const logs=[],original=console.error;console.error=(...args)=>logs.push(args);try{await f.service.conversation();}finally{console.error=original;}assert.equal(JSON.stringify(logs).includes('CANARY'),false);const observations=f.store.db.prepare('SELECT payload FROM run_observations UNION ALL SELECT payload FROM attempt_observations').all();assert.equal(JSON.stringify(observations).includes('CANARY'),false);assert.equal(f.store.db.prepare('SELECT terminal FROM run_observations').get().terminal,'provider_error');});
test('actual parser null structured output is invalid output, cancellation has unknown usage',async t=>{const f=await sdkFixture(t);const events=success();events[1].item.text='null';await f.events(events);await assert.rejects(f.agent.run('123','Synthetic input'));assert.equal(receipts(f.store).at(-1).reason,'invalid_output');const ctrl=new AbortController();ctrl.abort(new Error('ABORT_PRIVATE_CANARY'));await assert.rejects(f.agent.run('123','Synthetic input','main',[],ctrl.signal));assert.equal(receipts(f.store).at(-1).reason,'cancelled');assert.equal(receipts(f.store).at(-1).usage,null);assert.equal(JSON.stringify(receipts(f.store)).includes('ABORT_PRIVATE_CANARY'),false);});
test('constructor failures and unsupported run schemas cannot fail user execution or persist private fields',()=>{const unavailable=new Observations({db:{exec(){throw new Error('PRIVATE_INIT_CANARY');}}});assert.equal(unavailable.ready,false);assert.doesNotThrow(()=>unavailable.finishRun(unavailable.run(),'completed'));assert.ok(unavailable.dropped>0);const {store,o}=fixture(),r=o.run();o.finishRun(r,'completed');const p=JSON.parse(store.db.prepare('SELECT payload FROM run_observations').get().payload);assert.equal(o.recordRun({...p,schema_version:2}),false);assert.equal(o.recordRun({...p,unknown:'PRIVATE_RUN_CANARY'}),false);assert.equal(o.recordRun({...p,toolCounts:{PRIVATE_RUN_CANARY:1}}),false);assert.equal(JSON.stringify(store.db.prepare('SELECT payload FROM run_observations').all()).includes('PRIVATE_RUN_CANARY'),false);store.db.close();});
